export type IconGroup =
  | 'brands_media'
  | 'food_drink'
  | 'transport'
  | 'bills_utilities'
  | 'shopping_lifestyle'
  | 'health_education'
  | 'income_finance'
  | 'other';

export type CategoryIconDefinition = {
  id: string; // e.g. 'fa6:tiktok'
  nameVi: string;
  nameEn: string;
  category: IconGroup;
  library: 'fa6' | 'mci' | 'lucide';
  iconName: string;
  tags: string[];
};

export const CATEGORY_ICON_GROUPS: { id: IconGroup; labelVi: string; labelEn: string }[] = [
  { id: 'brands_media', labelVi: 'MXH & Giải trí', labelEn: 'Social & Media' },
  { id: 'food_drink', labelVi: 'Ăn uống', labelEn: 'Food & Drink' },
  { id: 'transport', labelVi: 'Di chuyển', labelEn: 'Transport' },
  { id: 'bills_utilities', labelVi: 'Hóa đơn', labelEn: 'Bills & Utilities' },
  { id: 'shopping_lifestyle', labelVi: 'Mua sắm', labelEn: 'Shopping' },
  { id: 'health_education', labelVi: 'Sức khỏe & Học tập', labelEn: 'Health & Edu' },
  { id: 'income_finance', labelVi: 'Thu nhập & Tài chính', labelEn: 'Income & Finance' },
  { id: 'other', labelVi: 'Khác', labelEn: 'Other' },
];

export const CATEGORY_ICON_REGISTRY: readonly CategoryIconDefinition[] = [
  // 1. Brands & Social Media
  {
    id: 'fa6:tiktok',
    nameVi: 'TikTok',
    nameEn: 'TikTok',
    category: 'brands_media',
    library: 'fa6',
    iconName: 'tiktok',
    tags: ['tiktok', 'tik tok', 'mxh', 'video', 'social', 'clip', 'dance'],
  },
  {
    id: 'fa6:spotify',
    nameVi: 'Spotify',
    nameEn: 'Spotify',
    category: 'brands_media',
    library: 'fa6',
    iconName: 'spotify',
    tags: ['spotify', 'nhac', 'music', 'podcast', 'audio', 'streaming'],
  },
  {
    id: 'fa6:youtube',
    nameVi: 'YouTube',
    nameEn: 'YouTube',
    category: 'brands_media',
    library: 'fa6',
    iconName: 'youtube',
    tags: ['youtube', 'yt', 'video', 'xem phim', 'clip', 'google'],
  },
  {
    id: 'fa6:facebook',
    nameVi: 'Facebook',
    nameEn: 'Facebook',
    category: 'brands_media',
    library: 'fa6',
    iconName: 'facebook',
    tags: ['facebook', 'fb', 'meta', 'mxh', 'social', 'ban be'],
  },
  {
    id: 'fa6:instagram',
    nameVi: 'Instagram',
    nameEn: 'Instagram',
    category: 'brands_media',
    library: 'fa6',
    iconName: 'instagram',
    tags: ['instagram', 'insta', 'ig', 'photo', 'story', 'anh'],
  },
  {
    id: 'fa6:apple',
    nameVi: 'Apple',
    nameEn: 'Apple',
    category: 'brands_media',
    library: 'fa6',
    iconName: 'apple',
    tags: ['apple', 'icloud', 'itunes', 'appstore', 'iphone', 'macbook'],
  },
  {
    id: 'fa6:google',
    nameVi: 'Google',
    nameEn: 'Google',
    category: 'brands_media',
    library: 'fa6',
    iconName: 'google',
    tags: ['google', 'gg', 'drive', 'play', 'gmail', 'cloud'],
  },
  {
    id: 'fa6:discord',
    nameVi: 'Discord',
    nameEn: 'Discord',
    category: 'brands_media',
    library: 'fa6',
    iconName: 'discord',
    tags: ['discord', 'chat', 'game', 'voice', 'server', 'nitro'],
  },
  {
    id: 'fa6:steam',
    nameVi: 'Steam',
    nameEn: 'Steam',
    category: 'brands_media',
    library: 'fa6',
    iconName: 'steam',
    tags: ['steam', 'game', 'valve', 'pc', 'nap game'],
  },
  {
    id: 'fa6:twitch',
    nameVi: 'Twitch',
    nameEn: 'Twitch',
    category: 'brands_media',
    library: 'fa6',
    iconName: 'twitch',
    tags: ['twitch', 'stream', 'livestream', 'game'],
  },
  {
    id: 'fa6:film',
    nameVi: 'Netflix / Phim',
    nameEn: 'Movies / Netflix',
    category: 'brands_media',
    library: 'fa6',
    iconName: 'film',
    tags: ['netflix', 'phim', 'movie', 'cinema', 'rap chieu', 'dien anh', 've'],
  },
  {
    id: 'fa6:gamepad',
    nameVi: 'Trò chơi / Game',
    nameEn: 'Gaming',
    category: 'brands_media',
    library: 'fa6',
    iconName: 'gamepad',
    tags: ['game', 'choi game', 'ps5', 'playstation', 'nintendo', 'xbox', 'giai tri'],
  },
  {
    id: 'fa6:music',
    nameVi: 'Âm nhạc',
    nameEn: 'Music',
    category: 'brands_media',
    library: 'fa6',
    iconName: 'music',
    tags: ['nhac', 'music', 'sound', 'bai hat', 'ca nhac', 'concert', 'show'],
  },

  // 2. Food & Drink
  {
    id: 'mci:silverware-fork-knife',
    nameVi: 'Ăn tiệm / Nhà hàng',
    nameEn: 'Dining & Restaurant',
    category: 'food_drink',
    library: 'mci',
    iconName: 'silverware-fork-knife',
    tags: ['an uong', 'nha hang', 'quan an', 'dining', 'food', 'an tiem', 'bua trua', 'bua toi'],
  },
  {
    id: 'fa6:mug-hot',
    nameVi: 'Cà phê & Trà',
    nameEn: 'Coffee & Tea',
    category: 'food_drink',
    library: 'fa6',
    iconName: 'mug-hot',
    tags: ['cafe', 'ca phe', 'tra sua', 'highland', 'phuc long', 'starbucks', 'tea', 'drink'],
  },
  {
    id: 'fa6:burger',
    nameVi: 'Đồ ăn nhanh',
    nameEn: 'Fast Food',
    category: 'food_drink',
    library: 'fa6',
    iconName: 'burger',
    tags: ['fast food', 'burger', 'kfc', 'lotteria', 'ga ran', 'banh mi'],
  },
  {
    id: 'fa6:pizza-slice',
    nameVi: 'Pizza',
    nameEn: 'Pizza',
    category: 'food_drink',
    library: 'fa6',
    iconName: 'pizza-slice',
    tags: ['pizza', 'tiec', 'party', 'do au', 'an vat'],
  },
  {
    id: 'fa6:beer-mug-empty',
    nameVi: 'Bia & Rượu / Bar',
    nameEn: 'Beer & Drinks',
    category: 'food_drink',
    library: 'fa6',
    iconName: 'beer-mug-empty',
    tags: ['bia', 'beer', 'nhau', 'bar', 'pub', 'ruou', 'lien hoan'],
  },
  {
    id: 'mci:cupcake',
    nameVi: 'Bánh ngọt & Tráng miệng',
    nameEn: 'Dessert & Bakery',
    category: 'food_drink',
    library: 'mci',
    iconName: 'cupcake',
    tags: ['banh', 'bakery', 'cake', 'kem', 'ice cream', 'trang mieng', 'an vat'],
  },
  {
    id: 'mci:fruit-cherries',
    nameVi: 'Trái cây & Nông sản',
    nameEn: 'Fruits & Produce',
    category: 'food_drink',
    library: 'mci',
    iconName: 'fruit-cherries',
    tags: ['trai cay', 'hoa qua', 'fruit', 'rau cu', 'nong san', 'sach'],
  },

  // 3. Transport
  {
    id: 'fa6:motorcycle',
    nameVi: 'Xe máy',
    nameEn: 'Motorbike',
    category: 'transport',
    library: 'fa6',
    iconName: 'motorcycle',
    tags: ['xe may', 'xe', 'motorbike', 'honda', 'yamaha', 'gui xe', 'sua xe'],
  },
  {
    id: 'fa6:car-side',
    nameVi: 'Ô tô / Taxi / Grab',
    nameEn: 'Car & Taxi',
    category: 'transport',
    library: 'fa6',
    iconName: 'car-side',
    tags: ['oto', 'o to', 'car', 'taxi', 'grab', 'be', 'xanh sm', 'lai xe'],
  },
  {
    id: 'fa6:gas-pump',
    nameVi: 'Xăng dầu',
    nameEn: 'Fuel / Gas',
    category: 'transport',
    library: 'fa6',
    iconName: 'gas-pump',
    tags: ['xang', 'dau', 'fuel', 'gas', 'cay xang', 'petrolimex'],
  },
  {
    id: 'fa6:bus',
    nameVi: 'Xe buýt / Xe khách',
    nameEn: 'Bus',
    category: 'transport',
    library: 'fa6',
    iconName: 'bus',
    tags: ['xe buyt', 'bus', 'xe khach', 'phuong tien cong cong'],
  },
  {
    id: 'fa6:plane',
    nameVi: 'Máy bay / Du lịch',
    nameEn: 'Flight & Travel',
    category: 'transport',
    library: 'fa6',
    iconName: 'plane',
    tags: ['may bay', 'plane', 'flight', 've may bay', 'du lich', 'travel', 'san bay'],
  },
  {
    id: 'fa6:train',
    nameVi: 'Tàu hỏa / Metro',
    nameEn: 'Train & Metro',
    category: 'transport',
    library: 'fa6',
    iconName: 'train',
    tags: ['tau', 'tau hoa', 'train', 'metro', 'duong sat'],
  },

  // 4. Bills & Utilities
  {
    id: 'fa6:bolt',
    nameVi: 'Tiền điện',
    nameEn: 'Electricity',
    category: 'bills_utilities',
    library: 'fa6',
    iconName: 'bolt',
    tags: ['dien', 'tien dien', 'evn', 'electricity', 'nang luong', 'hoa don'],
  },
  {
    id: 'fa6:faucet-drip',
    nameVi: 'Tiền nước',
    nameEn: 'Water Bill',
    category: 'bills_utilities',
    library: 'fa6',
    iconName: 'faucet-drip',
    tags: ['nuoc', 'tien nuoc', 'water', 'sinh hoat', 'hoa don'],
  },
  {
    id: 'fa6:wifi',
    nameVi: 'Internet & Wifi',
    nameEn: 'Internet / Wifi',
    category: 'bills_utilities',
    library: 'fa6',
    iconName: 'wifi',
    tags: ['wifi', 'internet', 'mang', 'fpt', 'viettel', 'vnpt', 'cuoc'],
  },
  {
    id: 'fa6:mobile-screen',
    nameVi: 'Điện thoại & 4G/5G',
    nameEn: 'Mobile & Data',
    category: 'bills_utilities',
    library: 'fa6',
    iconName: 'mobile-screen',
    tags: ['dien thoai', 'nap the', 'the cao', '4g', '5g', 'data', 'cuoc goi'],
  },
  {
    id: 'fa6:house',
    nameVi: 'Tiền nhà & Chung cư',
    nameEn: 'Rent & Housing',
    category: 'bills_utilities',
    library: 'fa6',
    iconName: 'house',
    tags: ['nha', 'thue nha', 'tien phong', 'chung cu', 'phi quan ly', 'house', 'rent'],
  },
  {
    id: 'mci:shield-check',
    nameVi: 'Bảo hiểm',
    nameEn: 'Insurance',
    category: 'bills_utilities',
    library: 'mci',
    iconName: 'shield-check',
    tags: ['bao hiem', 'insurance', 'y te', 'nhan tho', 'xe may', 'an toan'],
  },
  {
    id: 'mci:receipt-text',
    nameVi: 'Hóa đơn chung',
    nameEn: 'General Bill',
    category: 'bills_utilities',
    library: 'mci',
    iconName: 'receipt-text',
    tags: ['hoa don', 'bill', 'bien lai', 'dich vu', 'phi'],
  },

  // 5. Shopping & Lifestyle
  {
    id: 'fa6:cart-shopping',
    nameVi: 'Siêu thị & Chợ',
    nameEn: 'Groceries & Market',
    category: 'shopping_lifestyle',
    library: 'fa6',
    iconName: 'cart-shopping',
    tags: ['sieu thi', 'cho', 'groceries', 'winmart', 'coop', 'bach hoa', 'di cho'],
  },
  {
    id: 'fa6:bag-shopping',
    nameVi: 'Mua sắm & Shopee',
    nameEn: 'Shopping & E-commerce',
    category: 'shopping_lifestyle',
    library: 'fa6',
    iconName: 'bag-shopping',
    tags: ['mua sam', 'shopping', 'shopee', 'lazada', 'tiki', 'online', 'hang'],
  },
  {
    id: 'fa6:shirt',
    nameVi: 'Quần áo & Thời trang',
    nameEn: 'Clothing & Fashion',
    category: 'shopping_lifestyle',
    library: 'fa6',
    iconName: 'shirt',
    tags: ['quan ao', 'thoi trang', 'fashion', 'clothes', 'ao', 'vay', 'dam'],
  },
  {
    id: 'mci:shoe-sneaker',
    nameVi: 'Giày dép & Phụ kiện',
    nameEn: 'Shoes & Footwear',
    category: 'shopping_lifestyle',
    library: 'mci',
    iconName: 'shoe-sneaker',
    tags: ['giay', 'dep', 'sneaker', 'shoes', 'phu kien', 'tui'],
  },
  {
    id: 'mci:spray-bottle',
    nameVi: 'Mỹ phẩm & Làm đẹp',
    nameEn: 'Beauty & Cosmetics',
    category: 'shopping_lifestyle',
    library: 'mci',
    iconName: 'spray-bottle',
    tags: ['my pham', 'lam dep', 'beauty', 'spa', 'skincare', 'son', 'cat toc', 'nail'],
  },
  {
    id: 'fa6:couch',
    nameVi: 'Nội thất & Gia dụng',
    nameEn: 'Furniture & Home',
    category: 'shopping_lifestyle',
    library: 'fa6',
    iconName: 'couch',
    tags: ['noi that', 'gia dung', 'furniture', 'ban ghe', 'giuong', 'trang tri'],
  },
  {
    id: 'fa6:laptop',
    nameVi: 'Công nghệ & Điện tử',
    nameEn: 'Electronics',
    category: 'shopping_lifestyle',
    library: 'fa6',
    iconName: 'laptop',
    tags: ['cong nghe', 'laptop', 'may tinh', 'dien tu', 'tech', 'gadget'],
  },

  // 6. Health & Education
  {
    id: 'fa6:heart-pulse',
    nameVi: 'Sức khỏe & Y tế',
    nameEn: 'Health & Medical',
    category: 'health_education',
    library: 'fa6',
    iconName: 'heart-pulse',
    tags: ['suc khoe', 'y te', 'kham benh', 'thuoc', 'pharmacy', 'benh vien', 'bac si'],
  },
  {
    id: 'fa6:dumbbell',
    nameVi: 'Thể thao & Gym',
    nameEn: 'Fitness & Gym',
    category: 'health_education',
    library: 'fa6',
    iconName: 'dumbbell',
    tags: ['gym', 'the thao', 'fitness', 'the hinh', 'yoga', 'chay bo', 'boi'],
  },
  {
    id: 'fa6:book-open',
    nameVi: 'Sách & Đọc',
    nameEn: 'Books & Reading',
    category: 'health_education',
    library: 'fa6',
    iconName: 'book-open',
    tags: ['sach', 'book', 'truyen', 'doc sach', 'giao trinh'],
  },
  {
    id: 'fa6:graduation-cap',
    nameVi: 'Học tập & Học phí',
    nameEn: 'Education & Tuition',
    category: 'health_education',
    library: 'fa6',
    iconName: 'graduation-cap',
    tags: ['hoc', 'hoc tap', 'hoc phi', 'education', 'khoa hoc', 'truong', 'chung chi'],
  },
  {
    id: 'fa6:paw',
    nameVi: 'Thú cưng',
    nameEn: 'Pets',
    category: 'health_education',
    library: 'fa6',
    iconName: 'paw',
    tags: ['thu cung', 'cho', 'meo', 'pet', 'thuc an meo', 'thu y'],
  },

  // 7. Income & Finance
  {
    id: 'fa6:money-bill-wave',
    nameVi: 'Tiền lương',
    nameEn: 'Salary',
    category: 'income_finance',
    library: 'fa6',
    iconName: 'money-bill-wave',
    tags: ['luong', 'tien luong', 'salary', 'thu nhap', 'cong ty'],
  },
  {
    id: 'fa6:gift',
    nameVi: 'Tiền thưởng & Quà',
    nameEn: 'Bonus & Gifts',
    category: 'income_finance',
    library: 'fa6',
    iconName: 'gift',
    tags: ['thuong', 'bonus', 'li xi', 'qua tang', 'gift'],
  },
  {
    id: 'fa6:chart-line',
    nameVi: 'Đầu tư & Chứng khoán',
    nameEn: 'Investments',
    category: 'income_finance',
    library: 'fa6',
    iconName: 'chart-line',
    tags: ['dau tu', 'invest', 'chung khoan', 'co phieu', 'quy', 'crypto'],
  },
  {
    id: 'fa6:coins',
    nameVi: 'Tiền lãi & Cổ tức',
    nameEn: 'Interest & Dividends',
    category: 'income_finance',
    library: 'fa6',
    iconName: 'coins',
    tags: ['lai', 'tien lai', 'tiet kiem', 'co tuc', 'interest'],
  },
  {
    id: 'fa6:building-columns',
    nameVi: 'Ngân hàng',
    nameEn: 'Banking',
    category: 'income_finance',
    library: 'fa6',
    iconName: 'building-columns',
    tags: ['ngan hang', 'bank', 'chuyen khoan', 'giao dich'],
  },
  {
    id: 'fa6:gem',
    nameVi: 'Vàng & Trang sức',
    nameEn: 'Gold & Jewelry',
    category: 'income_finance',
    library: 'fa6',
    iconName: 'gem',
    tags: ['vang', 'gold', 'trang suc', 'tai san', 'kim cuong'],
  },
  {
    id: 'fa6:briefcase',
    nameVi: 'Làm thêm / Freelance',
    nameEn: 'Side Job / Freelance',
    category: 'income_finance',
    library: 'fa6',
    iconName: 'briefcase',
    tags: ['lam them', 'freelance', 'du an ngoai', 'kinh doanh', 'ban hang'],
  },
  {
    id: 'fa6:wallet',
    nameVi: 'Ví tiền / Khác',
    nameEn: 'Wallet / Other Income',
    category: 'income_finance',
    library: 'fa6',
    iconName: 'wallet',
    tags: ['vi', 'wallet', 'tien mat', 'thu nhap khac'],
  },

  // 8. Other / Miscellaneous
  {
    id: 'fa6:shapes',
    nameVi: 'Chi tiêu khác',
    nameEn: 'Other Expense',
    category: 'other',
    library: 'fa6',
    iconName: 'shapes',
    tags: ['khac', 'other', 'chi tieu khac', 'chung'],
  },
  {
    id: 'fa6:hand-holding-heart',
    nameVi: 'Từ thiện & Hiếu hỷ',
    nameEn: 'Charity & Donation',
    category: 'other',
    library: 'fa6',
    iconName: 'hand-holding-heart',
    tags: ['tu thien', 'ung ho', 'dam cuoi', 'mung', 'hieu hy', 'donation'],
  },
  {
    id: 'fa6:wrench',
    nameVi: 'Sửa chữa & Bảo trì',
    nameEn: 'Maintenance & Repair',
    category: 'other',
    library: 'fa6',
    iconName: 'wrench',
    tags: ['sua chua', 'bao tri', 'tho', 'repair', 'do nghe'],
  },
] as const;

export const DEFAULT_CATEGORY_ICON = 'fa6:shapes';
